In [1]:
import numpy as np 
import pandas as pd
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel
import scipy.stats as stats



In [2]:
data = pd.read_csv('Downloads/Sales_add.csv')
data

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

In [3]:
data.isnull().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [4]:
data1 = data.rename(columns ={'Sales_before_digital_add(in $)': 'Sales Before', 'Sales_After_digital_add(in $)': 'Sales After'})
data1

Month      Region      Manager  Sales Before  Sales After
0    Month-1  Region - A  Manager - A        132921       270390
1    Month-2  Region - A  Manager - C        149559       223334
2    Month-3  Region - B  Manager - A        146278       244243
3    Month-4  Region - B  Manager - B        152167       231808
4    Month-5  Region - C  Manager - B        159525       258402
5    Month-6  Region - A  Manager - B        137163       256948
6    Month-7  Region - C  Manager - C        130625       222106
7    Month-8  Region - A  Manager - A        131140       230637
8    Month-9  Region - B  Manager - C        171259       226261
9   Month-10  Region - C  Manager - B        141956       193735
10  Month-11  Region - B  Manager - C        159339       203175
11  Month-12  Region - A  Manager - A        178939       276279
12  Month-13  Region - B  Manager - A        145062       205180
13  Month-14  Region - A  Manager - A        151514       253131
14  Month-15  Region - C  Manager - A        147463       229336
15  Month-16  Region - A  Manager - B        177195       187305
16  Month-17  Region - A  Manager - C        140862       234908
17  Month-18  Region - C  Manager - B        167996       191517
18  Month-19  Region - B  Manager - A        132135       227040
19  Month-20  Region - A  Manager - B        152493       212579
20  Month-21  Region - B  Manager - A        147425       263388
21  Month-22  Region - A  Manager - C        130263       243020

# 1. INCREASE IN SALES AFTER STEPPING INTO DIGITAL MARKETING

In [5]:
# H0 = No increase in sales after stepping into digital marketing
# H1 = Increase in sales after stepping into digital marketing 
alpha = 0.05
t_value,p_value = stats.ttest_rel(data1['Sales After'], data1['Sales Before'])
print("The calculated t score & p-value are : \n \nt-value = %0.3f \np-value = %0.3f \n" % (t_value,p_value))

The calculated t score & p-value are : 
 
t-value = 12.091 
p-value = 0.000 



In [6]:
if (p_value > alpha):
    print("Fails to reject the null hypoyhesis")
else:
    print("Rejecting the null hypothesis")

Rejecting the null hypothesis


# 2. DEPENDENCY BETWEEN REGION AND MANAGER2.

In [7]:
# H0 = No relationship between regionn and manager
# H1 = There is a relationship between region and manager



In [8]:
data2 = pd.crosstab(data1['Region'],data['Manager'])
data2


Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [9]:
observed_values = data2.values
print('observed values:-\n',observed_values)

observed values:-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [11]:
value = stats.chi2_contingency(data2)
value

(3.050566893424036,
 0.5493991051158094,
 4,
 array([[4.09090909, 3.18181818, 2.72727273],
        [2.86363636, 2.22727273, 1.90909091],
        [2.04545455, 1.59090909, 1.36363636]]))

In [12]:
expected_value = value[3]
expected_value

array([[4.09090909, 3.18181818, 2.72727273],
       [2.86363636, 2.22727273, 1.90909091],
       [2.04545455, 1.59090909, 1.36363636]])

In [14]:
no_of_rows = len(data2.iloc[0:3,0])
no_of_columns = len(data2.iloc[0,0:3])
ddof = (no_of_rows-1)*(no_of_columns-1)
print('Degrees of Freedom:',ddof)
alpha = 0.05
from scipy.stats import chi2

Degrees of Freedom: 4


In [15]:
chi_square = sum([(o-e)**2./e for o,e in zip(observed_values,expected_value)])
chi_square_statistics = chi_square[0] + chi_square[1]
print('chi-Square statistics:',chi_square_statistics)
critical_value = chi2.ppf(q = 1-alpha,df = ddof)
print('Critical_value:',critical_value)

chi-Square statistics: 2.921995464852608
Critical_value: 9.487729036781154


In [16]:
p_value = 1-chi2.cdf(x = chi_square_statistics,df = ddof)
print('p_value:',p_value)
print('Significance Level:',alpha)
print('Degrees of Freedom:',ddof)

p_value: 0.5709629929220089
Significance Level: 0.05
Degrees of Freedom: 4


In [18]:
if (p_value > alpha):
    print('Fails to reject the null hypothesis')
else:
    print('Rejecting the null hypothesis')

Fails to reject the null hypothesis
